import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Texas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <video class="lozad" width="100%" autoplay="" loop="" playsinline="" id="video-one">
        <source src="https://texas-psdigital.vercel.app/assets/images/texas-home.mp4" type="video/mp4" />
      </video>
    </div>
  )
}
